### ISSUE TITLE
Update to CMSSW 7.4.13

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#71]
This is a follow-up of #38 with a todo list of remaining items:
- [x] Ensure that 7.4.12 and 7.4.10 branches are in sync ( #70 )
- [x] Update code to work on 7.4.13 ( #67 )
- [x] Update electron id: #72  ( https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Recipe_for_regular_users_for_7_4 )
- [x] Follow new MET recommendations: #73 ( https://hypernews.cern.ch/HyperNews/CMS/get/met/415.html)
- [x] Update to new JEC: #74 (not GT for the moment, https://hypernews.cern.ch/HyperNews/CMS/get/jes/558.html and https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC )
